### ISSUE TITLE
`Poetry Install` fails on Poetry version 1.8.2

### ISSUE THREAD

**Issue by MatthewJohnsonNPL** [OxfordIonTrapGroup/stabilizer-ui#24]
Trying to install from `poetry install` comes up with an SSL error on fetching `miniconf-mqtt` whilst trying to isntall `stabilizer` from the git.  I've tried a whole bunch of things including `certifi` and editing the certificate.pem file (thinking it was an internal firewall issue) to no avail.  I believe this is caused by the virtual environment created by poetry, used to install from { git } links in the `pyproject.toml`.  

![image](https://github.com/OxfordIonTrapGroup/stabilizer-ui/assets/174029244/40044e9b-995b-4d10-a491-a133fe25c093)

Following the instructions [here](https://python-poetry.org/docs/dependency-specification/#git-dependencies) and enabling the system git client, instead of the Dulwich version for Poetry >1.2:
```
poetry config experimental.system-git-client true
```
 seemed to circumvent this issue for now.  Unsure if this is an issue on just my side or more to do with the way the `poetry.lock` has been configured.  It may work if the stabilizer dependencies are written out explicitly, or specifying the SSL in the lock file? 

Apologies, as this is my first issue ever created, and I'm not an expert when it comes to poetry.

**Comment by ayushagrawal2** [comment]
Hi Matthew, thanks for raising this issue.

This seems like an issue with OpenSSL not being installed on your PC as opposed to a toml config issue. Poetry by default requires SSL authentication, and while you could turn it off for a specific repository foo using `poetry config certificates.foo.cert false`, this is NOT recommended. Try checking if OpenSSL is installed on your PC (`openssl version -a` on cmd)? Consider installing a recent version if it isn't there or is outdated.

Also, do not manually edit the lock file unless you know what you're doing. It might break things or give issues when you try to update the lock file.

**Comment by MatthewJohnsonNPL** [comment]
Ah, interesting. I do indeed not have openssl on my machine - probably why `certifi` didnt make a difference.  Curious as to why the `system-git-client true` then worked in the end... Thanks.

**Comment by ayushagrawal2** [comment]
Poetry uses dulwich to interact with git without relying on a git installation on the PC. Setting this to true uses the git on your PC - presumably they are dealt with differently

**Comment by MatthewJohnsonNPL** [comment]
Then this sounds to me like a firewall issue. I need to look into Poetry more to get the client setup then.  Thanks.
